[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = [ "<C-n>" ]
run = '''
  shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''

[[manager.prepend_keymap]]
on   = [ "y" ]
run = [ "yank", '''
	shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''' ]
